workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        BUNDLE_ID: "com.ios.ratedly"
      flutter: 3.27.4
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - ahmadarafeh9@gmail.com
        notify:
          success: true
          failure: true
